spring:
  application:
    name: example-app
  main:
    lazy-initialization: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sofast?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
#  jackson:
#    serialization:
#      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
#      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
#      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
#      fail-on-empty-beans: false # 允许序列化无属性的 Bean
#    datatype:
#      enum:
#        write-enums-to-lowercase: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - cc.sofast.biz.component
        - cc.sofast.practice
  cache:
    disabled: true

knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-dynamic-parameter: true

sofast:
  rbac:
    web:
      enabled: true
